{% set version = "4.4.6" %}

{% set variant = "openblas" %}


package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz
  sha256: 7f22509d87ada8506580d537efde79cf90e28e228355c18b8bf603aad1a2d7b6

build:
  skip: true  # [win]
  number: 202
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - tbb

  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libamd.a"
    - test -f "${PREFIX}/lib/libbtf.a"
    - test -f "${PREFIX}/lib/libcamd.a"
    - test -f "${PREFIX}/lib/libccolamd.a"
    - test -f "${PREFIX}/lib/libcholmod.a"
    - test -f "${PREFIX}/lib/libcolamd.a"
    - test -f "${PREFIX}/lib/libcxsparse.a"
    - test -f "${PREFIX}/lib/libklu.a"
    - test -f "${PREFIX}/lib/libldl.a"
    - test -f "${PREFIX}/lib/librbio.a"
    - test -f "${PREFIX}/lib/libspqr.a"
    - test -f "${PREFIX}/lib/libsuitesparseconfig.a"
    - test -f "${PREFIX}/lib/libumfpack.a"

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: BSD 3-Clause or LGPL v2.1, LGPL v2.1, GPL v2 (UMFPACK)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
