{% set version = "5.3.0" %}

{% set variant = "openblas" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz
  sha256: 90e69713d8c454da5a95a839aea5d97d8d03d00cc1f667c4bdfca03f640f963d

build:
  skip: true  # [win]
  number: 0
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - tbb
    - cmake
    - metis 5.1.*

  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - tbb
    - metis 5.1.*

test:
  commands:
    - test -f ${PREFIX}/lib/libamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libbtf${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libccolamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcholmod${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcolamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcxsparse${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libklu${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libldl${SHLIB_EXT}
    - test -f ${PREFIX}/lib/librbio${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libspqr${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsuitesparseconfig${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libumfpack${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libamd.a
    - test -f ${PREFIX}/lib/libbtf.a
    - test -f ${PREFIX}/lib/libcamd.a
    - test -f ${PREFIX}/lib/libccolamd.a
    - test -f ${PREFIX}/lib/libcholmod.a
    - test -f ${PREFIX}/lib/libcolamd.a
    - test -f ${PREFIX}/lib/libcxsparse.a
    - test -f ${PREFIX}/lib/libklu.a
    - test -f ${PREFIX}/lib/libldl.a
    - test -f ${PREFIX}/lib/librbio.a
    - test -f ${PREFIX}/lib/libspqr.a
    - test -f ${PREFIX}/lib/libsuitesparseconfig.a
    - test -f ${PREFIX}/lib/libumfpack.a

    - conda inspect linkages -p ${PREFIX} suitesparse  # [not win]
    - conda inspect objects -p ${PREFIX} suitesparse  # [osx]

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
