{% set version = "7.7.0" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ version }}.tar.gz
  sha256: 529b067f5d80981f45ddf6766627b8fc5af619822f068f342aab776e683df4f3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("suitesparse") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - libblas
    - libcblas
    - liblapack
    - tbb-devel
    - metis
    - mpfr

test:
  commands:
    # graphblas and mongoose are omitted
    - test ! -f ${PREFIX}/bin/mongoose  # [unix]
    - test ! -f ${PREFIX}/include/GraphBLAS.h  # [unix]
    - test ! -f ${PREFIX}/include/Mongoose.hpp  # [unix]
    - test ! -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libmongoose${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libgraphblas.a  # [unix]
    - test ! -f ${PREFIX}/lib/libmongoose.a  # [unix]

    - test -f ${PREFIX}/include/suitesparse/amd.h  # [unix]
    - test -f ${PREFIX}/include/suitesparse/umfpack.h  # [unix]
    {% for name in ['amd', 'btf', 'camd', 'ccolamd', 'cholmod', 'colamd', 'cxsparse', 'klu', 'ldl', 'rbio', 'spqr', 'suitesparseconfig', 'umfpack'] %}
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/lib{{ name }}.a  # [unix]
    {% endfor %}

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL-2.1-or-later AND BSD-3-Clause AND GPL-2.0-or-later AND Apache-2.0
  license_file: LICENSE.txt
  summary: A suite of sparse matrix algorithms
  dev_url: https://github.com/DrTimothyAldenDavis/SuiteSparse

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
