{% set bundle_version = "1.5.0" %}
{% set version = "5.4.0" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/v{{ bundle_version }}.tar.gz  # [win]
  sha256: 1e1a901e62ac368c8c525bd43cf900e2e1133d2b20a58d5254561bb585af9a9c  # [win]
  patches:
    - gh_56.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14 or win32 or unix]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke

test:
  commands:
    {% set suitesparse_libs = [
        "amd",
        "btf",
        "camd",
        "ccolamd",
        "cholmod",
        "colamd",
        "cxsparse",
        "klu",
        "ldl",
        "spqr",
        "umfpack"
    ] %}
    {% for each_lib in suitesparse_libs %}
    - if not exist %LIBRARY_PREFIX%\\bin\\{{ each_lib }}.dll exit 1                        # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\{{ each_lib }}.lib exit 1                        # [win]
    {% endfor %}

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  license_file: SuiteSparse/LICENSE.txt
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - seanyen
