travis:
  secure:
    BINSTAR_TOKEN: VV+0k8m2Vvi2F4LnIycwrbdkLPEnxZe16ndk3bwbOs5zg7OMPfp9xb+NVft9wjHgedbEr/qaZUXjU71zC1xkw71jZnxKEfsjepFturnVWQuv8MskxZVXKd/kFe2mEbkzmYx61/Ee2U63/Ln5BbmHadaVVs9a3P8Dol52OcSksAWenUC5ywZY5vWYnIaolDAqCEifyO7uztBLd9fqMz6diXW0SSIaQD7u6kH+kQuNjD3LXswqIt2FLFrj4sBOKAanwZaRnnpriDxGBnXnz8i3Z7JiWp7ZVq93xQ6rsw5Qw+yZBaGWgvQrNkhQje5ttylCyRLWfd3VaOH8ianig18jCM25U+AQm542r/cSbDSxtCBDglu0j1Mkjc68LKLYTMVVk9g0FdrEQkJpuRHEkALo7cONVVRm37kKBz1c7WfFjlyHNcKtkneLlo6qtecZlXVhnpsXO7WBMrBf74sHZkNhwXkC++b0hHGtlcl6wVVc5mYHPog5Nooe9ZXL8G7FJxCrMIe++L27n1ob8nLsONjIZv7234cwzDdpMRLo4cDO6HLa4O1S0MoNl2qP40S1J2hwOaEZRHyXU2G4FVEKLjQ0lh0/cCT5MTQyLLws5QuUjz9zpzF/VDx0UAVgSqdtr00FILnzNX0Ktk5+1TeodIl/p0LWvljfUSkh1IOZodRyhuk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
