travis:
  secure:
    BINSTAR_TOKEN: 1KQjE9qd7CAPSdxhBdJC3TPc4UoRB9WZ6wDr/q0/2Me3rLJ26mGAubr3gLx4pcyJ9NDr+CbxSTGldnM4HHaw3k3jeu/cwdrg8G4dNJ28SzGS8nuc9eQj3gAAKqMDuwOHrYBCAuZpPWgXALYQHSuR79pCVgUpWgZ8gYH+fjTQjaXEadVjd1MevExa/VOQ5x73d06t0PwrAHZeUsPphIcpi5p6i1I5ZiUdU8r7T23+eokY/kcB0pVr/YH0lkqODhqSE3t7pP/7y2nf/sBxLB+7QVMCtzQTjGH5Ged18u/9z8GEJ7d1dAqzSYG1riBAVycgtPtNX4aJAuPLw4lQ2ewKegOXJQ1cVRmxXhwxyAPYWoTu8HtEm5wbIg4mpD+YXDy+i6tWfYh7r0uawOa/I72lvT3EnjfaxV+HPVc3ZF7MNY3rMeGfxcaVk5Pt/ewcFy2awTtc+TrZJU0mHVddvsEcdDEcdIBrUC5OwTmOwKyIsU3chut86081fsNU0qOPl3hH2q1g8BFcU4CM6RWoumAWazdR389vy8s2F6iXpMrOpVLpcATfCOLL9X21zOLKCmwl7GiNAFoiApg/+uW3cAHqUzZhhWzppaBQB1pG29gK838uckRyksBrpl8H+0Ct1F8yDGwCsSUMVzkfv3jOO6B7OqmdfG37PnpZm1qldy6JyOc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
